parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     cowboys
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

# S3 Configuration
    S3_use_ssl:  true
    S3_verify_peer: true
    S3_access_key: AKIAJW77I5OAC63UVOXQ
    S3_secret_key: 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