parameters:
    database_driver:   pdo_mysql
    database_host:      cowboyduel.c6algyr0odj4.eu-west-1.rds.amazonaws.com
    database_port:     3306
    database_name:   duels_v201
    database_user:     duels
    database_password: FTa9aueWYmWub8wb

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt