services:
    kernel.listener.UpdateWithTimeListener:
        class: CowboyDuel\ApiBundle\Listener\UpdateWithTimeListener
        tags: [{name: kernel.event_listener, event: kernel.controller, method: onKernelController}]
        arguments: [@service_container, @doctrine.orm.entity_manager] 

parameters:
    # S3 Configuration
    S3_use_ssl:  true
    S3_verify_peer: true
    S3_access_key: AKIAJW77I5OAC63UVOXQ
    S3_secret_key: 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
    S3_file_upload: bundles/cowboyduelapi/uploads/scriptJson.txt
    S3_uri: top.scriptJson