services:
    CowboyDuel.UpdateListTopUsers:
        class:  CowboyDuel\ApiBundle\DependencyInjection\UpdateListTopUsers
        arguments: [@service_container, @doctrine.orm.entity_manager]
    CowboyDuel.PushNotifications:
        class:  CowboyDuel\ApiBundle\Libraries\PushNotifications
        arguments: [@service_container]
    CowboyDuel.Logger:
        class: Monolog\Logger
        arguments: [my_info]
        calls:
            - [pushHandler, [@CowboyDuel.Logger_handler]]
    CowboyDuel.Logger_handler:
        class: Monolog\Handler\StreamHandler
        arguments: [%kernel.root_dir%/logs/CowboyDuelLogger.log, 100]

parameters:
    # S3 Configuration
    S3_use_ssl:  true
    S3_verify_peer: true
    S3_access_key: AKIAJW77I5OAC63UVOXQ
    S3_secret_key: 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
    # S3 file
    S3_type_file: .json

    S3_topBoard_file_upload: bundles/cowboyduelapi/uploads/top.json.txt
    S3_topBoard_uri: top_board

    S3_listOfStoreItems_file_upload: bundles/cowboyduelapi/uploads/list_of_store_items.json.txt
    S3_listOfStoreItems_uri: list_of_store_items

    S3_listOfStoreItemsRetina_file_upload: bundles/cowboyduelapi/uploads/list_of_store_items_retina.json.txt
    S3_listOfStoreItemsRetina_uri: list_of_store_items_retina
    
    S3_bot_file_upload: bundles/cowboyduelapi/uploads/bot.json.txt
    S3_bot_uri: bot

    # Facebook Configuration
    facebook_appId: 284932561559672
    facebook_secret: 985311896c75dba974b8171e2bf76799